### ISSUE TITLE
MacOS nightly build 启动崩溃

### ISSUE THREAD

**Issue by serialcode9527** [ejoy/ant#164]
我尝试在自己的苹果电脑上（M1芯片）构建，遇到[问题](https://github.com/ejoy/ant/issues/150)，还没解决，想用官方构建跑一下，结果跑不起来，运行崩溃：

```
:)) ./bin/macos/release/ant test/simple/main.lua
dyld[21049]: Symbol not found: __ZNSt3__18to_charsEPcS0_d
  Referenced from: <DFF1E814-2CE0-3D56-AAED-3541BE9A0017> /Users/dmx/Downloads/ant-macos-arm64/bin/macos/release/ant (built for macOS 14.0 which is newer than running OS)
  Expected in:     <AE8EA4B2-B8FD-33E3-A0AF-0B7485AB97C0> /usr/lib/libc++.1.dylib
[1]    21049 abort      ./bin/macos/release/ant test/simple/main.lua

```

系统是MacOS 13.0 M2芯片
查看了下 `/usr/lib` 下面确实没有`libc++.1.dylib`

去同事的M3芯片，MacOS 14.4 系统上，`/usr/lib` 下面也没有`libc++.1.dylib`

是不是编译构建的机器环境和大多数arm芯片的mac的环境不太一样？

**Comment by actboy168** [comment]
目前macos最低要求是13.3。macos兼容低版本远比windows，加之没有这么多测试环境。

https://github.com/ejoy/ant/blob/49c94effdbe180392405a161fa4030d11e493632/make.lua#L39

**Comment by serialcode9527** [comment]
重新在macos 14上面试了下，可以正常运行
