### ISSUE TITLE
MSVC编译后，执行打开编辑器命令没有任何反应

### ISSUE THREAD

**Issue by lragon** [ejoy/ant#33]
![image](https://github.com/ejoy/ant/assets/2757255/a8967769-ff21-43a9-8f68-026f55a49a37)

**Comment by aimoonchen** [comment]
@lragon  已修复，更新一下就好。
现在我们在编辑器里面都是操作一个游戏项目目录，可以带上命令行参数指定一个游戏项目，例如：
bin/msvc/debug/lua.exe tools/editor/main.lua D:/Github/vaststars2/startup
也可以不带命令行参数，表示空工程，现阶段工程的概念还不完善，可以会有其他问题。

**Comment by onlyfeng** [comment]
当前更新后再编译仍然运行无任何反应，尝试创建并带入一个空工程目录指定启动也是一样。（另启动 test/simple/main.lua 也是无任何反应）
（编译 debug 版本运行会有 Microsoft Visual C++ Runtime Library -- Debug Error! 的弹框报错）(Windows 10 系统, Visual Studio 2022 版本)

**Comment by aimoonchen** [comment]
![editor](https://github.com/ejoy/ant/assets/1982418/50f136dc-1876-4b51-b07c-101d81181053)

@onlyfeng @lragon 修复好了，可以在编辑器里面打开测试工程了：
bin/msvc/debug/lua.exe tools/editor/main.lua D:/Github/ant/test/simple
