### ISSUE TITLE
Editor crash when click menu item "Edit > Project Setting"

### ISSUE THREAD

**Issue by shar0** [ejoy/ant#40]
System: Windows 11
Represents step:
1. Build with luamake all --mode release
2. Open Editor
3. Click menu item Edit > Project Setting
4. Editor freeze and show Error log.

![image](https://github.com/ejoy/ant/assets/1460808/a6083492-ba55-43b0-b17f-0d38e112e3aa)

**Comment by aimoonchen** [comment]
I will rework project setting later.

**Comment by shar0** [comment]
Solved in https://github.com/ejoy/ant/commit/d9b7f8922ee861fef61795108238a84304e12a68
