### ISSUE TITLE
Editor crash when set 3D Cube object render layer to "ui_layer"

### ISSUE THREAD

**Issue by shar0** [ejoy/ant#41]
System: Windows 11
Represents step:
1. Build with luamake all --mode release
2. Open Editor
3. "+ Create" > Geometry > Cube
4. Select "cube1" in Entity

![image](https://github.com/ejoy/ant/assets/1460808/fcc4b035-63ec-4ff0-a91b-940d07ed2fbb)

6. Set render layer to "ui_stage" in inspector
7. Editor freeze and show Error log.

![image](https://github.com/ejoy/ant/assets/1460808/ee2554f6-574a-446e-a61b-e162b735e3bb)

**Comment by aimoonchen** [comment]
I will check the engine interface.

**Comment by shar0** [comment]
Solved in https://github.com/ejoy/ant/commit/d9b7f8922ee861fef61795108238a84304e12a68
