### ISSUE TITLE
Editor memory leaks when toggle maximize window.

### ISSUE THREAD

**Issue by shar0** [ejoy/ant#44]
System: Windows 11
Represents step:
1. Build with luamake all --mode release
2. Open Editor
3. Click "maximize" in application title bar, and repeat this step, each click will increase about 1~300M memory usage.
![image](https://github.com/ejoy/ant/assets/1460808/d63dd409-649f-4e4d-bfca-2f11b4654f37)
![image](https://github.com/ejoy/ant/assets/1460808/6550778b-bc79-444d-afb4-2679757f02c2)
![image](https://github.com/ejoy/ant/assets/1460808/a1fb656f-6392-44d9-8749-8e359082fd71)
![image](https://github.com/ejoy/ant/assets/1460808/b97c1b6d-a543-49f1-ae5d-f0216d7fd835)
![image](https://github.com/ejoy/ant/assets/1460808/e160b9bf-868a-4fe6-baf1-b4296317a9c4)

Memory usage will slowly to decrease, but only decrease 20% and stops.

**Comment by pourtheworld** [comment]
fixed in [#cef6d27](https://github.com/ejoy/ant/commit/cef6d270ce60854db71743614dd5642b6d35497a)
