### ISSUE TITLE
代码复制重复问题

### ISSUE THREAD

**Issue by soulim2040** [ejoy/ant#81]
大版本67d67ad15358b483d35ed31f06af979053b2a5dc <2024/1/31 12:21:35>
文件路径 ant\runtime\common\modules.c 109行

{ "ltask.bootstrap", luaopen_ltask_bootstrap}, 与108行重复，
应修正为  { "ltask.root", luaopen_ltask_root},

**Comment by actboy168** [comment]
把重复的删除就行了，ltask.root是不用暴露出来的。
